"""Tests for Bloque 20 campaign domain models (B20-T01)."""

from __future__ import annotations

import pytest

from packages.domain.campaign_models import (
    CampaignState,
    CampaignClockState,
    CampaignPlayer,
    Campaign,
    PlayerCharacterProfile,
    CampaignClock,
    _now,
    _parse_enum,
    _parse_list,
    _parse_int,
    _parse_str,
    _parse_dict,
)


# ═══════════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════════


class TestHelpers:
    def test_now_returns_iso_string(self):
        ts = _now()
        assert isinstance(ts, str)
        assert "T" in ts
        assert len(ts) >= 20

    def test_parse_list_with_none(self):
        assert _parse_list(None) == []

    def test_parse_list_with_list(self):
        assert _parse_list([1, 2]) == [1, 2]

    def test_parse_list_with_string(self):
        assert _parse_list("not a list") == []

    def test_parse_str_with_str(self):
        assert _parse_str("hello") == "hello"

    def test_parse_str_with_none(self):
        assert _parse_str(None) == ""

    def test_parse_int_with_int(self):
        assert _parse_int(42) == 42

    def test_parse_int_with_bool(self):
        # bool is a subclass of int in Python, but our guard
        # checks isinstance(value, bool) and returns 0
        assert _parse_int(True) == 0

    def test_parse_dict(self):
        assert _parse_dict({"a": 1}) == {"a": 1}
        assert _parse_dict(None) == {}
        assert _parse_dict("not dict") == {}


# ═══════════════════════════════════════════════════════════════════════
# CampaignState
# ═══════════════════════════════════════════════════════════════════════


class TestCampaignState:
    def test_four_values(self):
        states = list(CampaignState)
        assert len(states) == 4
        values = {s.value for s in states}
        assert values == {"activa", "pausada", "completada", "archivada"}

    def test_is_str_enum(self):
        assert CampaignState.ACTIVA == "activa"

    def test_parse_enum_valid(self):
        assert _parse_enum(CampaignState, "pausada", CampaignState.ACTIVA) == CampaignState.PAUSADA

    def test_parse_enum_invalid_returns_default(self):
        assert _parse_enum(CampaignState, "inventado", CampaignState.ACTIVA) == CampaignState.ACTIVA

    def test_parse_enum_with_member(self):
        assert _parse_enum(CampaignState, CampaignState.COMPLETADA, CampaignState.ACTIVA) == CampaignState.COMPLETADA


# ═══════════════════════════════════════════════════════════════════════
# CampaignClockState
# ═══════════════════════════════════════════════════════════════════════


class TestCampaignClockState:
    def test_four_values(self):
        states = list(CampaignClockState)
        assert len(states) == 4
        values = {s.value for s in states}
        assert values == {"active", "paused", "completed", "archived"}

    def test_is_str_enum(self):
        assert CampaignClockState.active == "active"

    def test_parse_enum_valid(self):
        assert _parse_enum(CampaignClockState, "paused", CampaignClockState.active) == CampaignClockState.paused

    def test_parse_enum_invalid_returns_default(self):
        assert _parse_enum(CampaignClockState, "bogus", CampaignClockState.active) == CampaignClockState.active


# ═══════════════════════════════════════════════════════════════════════
# CampaignPlayer
# ═══════════════════════════════════════════════════════════════════════


class TestCampaignPlayer:
    def test_defaults_and_autogenerated_id(self):
        p = CampaignPlayer(name="Juan")
        assert p.name == "Juan"
        assert p.id.startswith("plr_")
        assert len(p.id) == 12  # plr_ + 8 hex
        assert p.metadata == {}

    def test_explicit_id(self):
        p = CampaignPlayer(name="Ana", id="plr_custom01")
        assert p.id == "plr_custom01"

    def test_to_dict(self):
        p = CampaignPlayer(name="Juan", metadata={"role": "GM"})
        d = p.to_dict()
        assert d["name"] == "Juan"
        assert d["id"].startswith("plr_")
        assert d["metadata"]["role"] == "GM"
        assert len(d) == 3

    def test_from_dict(self):
        data = {"id": "plr_abc12345", "name": "María", "metadata": {"role": "player"}}
        p = CampaignPlayer.from_dict(data)
        assert p.id == "plr_abc12345"
        assert p.name == "María"
        assert p.metadata == {"role": "player"}

    def test_from_dict_empty(self):
        p = CampaignPlayer.from_dict({})
        assert p.name == ""
        # id is autogenerated by __post_init__ when passed ""
        assert p.id.startswith("plr_")

    def test_from_dict_missing_fields(self):
        p = CampaignPlayer.from_dict({"name": "Luis"})
        assert p.name == "Luis"
        # id is autogenerated because it's missing from data
        assert p.id.startswith("plr_")
        assert p.metadata == {}

    def test_roundtrip(self):
        p = CampaignPlayer(name="Ana", metadata={"note": "test"})
        j = p.to_dict()
        p2 = CampaignPlayer.from_dict(j)
        assert p2.name == p.name
        assert p2.id == p.id
        assert p2.metadata == p.metadata


# ═══════════════════════════════════════════════════════════════════════
# Campaign
# ═══════════════════════════════════════════════════════════════════════


class TestCampaign:
    def test_minimal_creation(self):
        c = Campaign(name="La Sombra")
        assert c.name == "La Sombra"
        assert len(c.id) == 12
        assert c.state == CampaignState.ACTIVA
        assert c.players == []
        assert c.player_character_entity_ids == []
        assert c.created_at != ""
        assert c.updated_at != ""

    def test_all_fields(self):
        player = CampaignPlayer(name="Juan")
        c = Campaign(
            id="abc123",
            name="Dragones",
            description="Una campaña épica",
            world_entity_id="ent_world_1",
            game_system="D&D 5e",
            tone="épico",
            genre="fantasía",
            state=CampaignState.PAUSADA,
            players=[player],
            player_character_entity_ids=["ent_gandalf"],
            session_entity_ids=["ent_sesion_1"],
            active_plot_entity_ids=["ent_trama_1"],
            active_faction_entity_ids=["ent_faccion_1"],
            active_location_entity_ids=["ent_ciudad_1"],
            secret_entity_ids=["ent_secreto_1"],
            clue_entity_ids=["ent_pista_1"],
            clock_ids=["clk_01"],
            private_notes=["Nota secreta"],
            public_summaries=["Resumen público"],
            visibility_rules={"gm_only": True},
            history=["Preparación inicial"],
            metadata={"campaign_number": 1},
        )
        assert c.id == "abc123"
        assert c.name == "Dragones"
        assert c.state == CampaignState.PAUSADA
        assert len(c.players) == 1
        assert c.players[0].name == "Juan"
        assert c.active_faction_entity_ids == ["ent_faccion_1"]
        assert c.visibility_rules == {"gm_only": True}
        assert c.created_at != ""
        assert c.updated_at != ""

    def test_to_dict(self):
        player = CampaignPlayer(name="Juan", id="plr_001")
        c = Campaign(
            id="cam_001",
            name="Test",
            state=CampaignState.ACTIVA,
            players=[player],
            active_faction_entity_ids=["ent_f1"],
            visibility_rules={"gm": True},
        )
        d = c.to_dict()
        assert d["id"] == "cam_001"
        assert d["name"] == "Test"
        assert d["state"] == "activa"
        assert d["players"][0]["name"] == "Juan"
        assert d["active_faction_entity_ids"] == ["ent_f1"]
        assert d["visibility_rules"] == {"gm": True}
        assert isinstance(d["history"], list)
        assert isinstance(d["clock_ids"], list)

    def test_from_dict(self):
        data = {
            "id": "cam_002",
            "name": "Test 2",
            "description": "Desc",
            "world_entity_id": "ent_world",
            "game_system": "Pathfinder",
            "tone": "sombrío",
            "genre": "terror",
            "state": "completada",
            "players": [{"id": "plr_x", "name": "Ana"}],
            "player_character_entity_ids": ["ent_pc1"],
            "session_entity_ids": [],
            "active_plot_entity_ids": [],
            "active_faction_entity_ids": ["ent_f1"],
            "active_location_entity_ids": [],
            "secret_entity_ids": [],
            "clue_entity_ids": [],
            "clock_ids": [],
            "private_notes": [],
            "public_summaries": [],
            "visibility_rules": {},
            "history": ["created"],
            "metadata": {},
            "created_at": "2026-06-01T00:00:00Z",
            "updated_at": "2026-06-01T00:00:00Z",
        }
        c = Campaign.from_dict(data)
        assert c.id == "cam_002"
        assert c.name == "Test 2"
        assert c.state == CampaignState.COMPLETADA
        assert len(c.players) == 1
        assert c.players[0].name == "Ana"
        assert c.world_entity_id == "ent_world"
        assert c.game_system == "Pathfinder"
        assert c.history == ["created"]

    def test_from_dict_empty(self):
        c = Campaign.from_dict({})
        assert c.name == ""
        # id is autogenerated by __post_init__
        assert len(c.id) == 12
        assert c.state == CampaignState.ACTIVA

    def test_from_dict_invalid_state_returns_default(self):
        c = Campaign.from_dict({"name": "X", "state": "inexistente"})
        assert c.state == CampaignState.ACTIVA

    def test_roundtrip(self):
        player = CampaignPlayer(name="Juan")
        c = Campaign(
            name="Roundtrip",
            description="Test roundtrip",
            world_entity_id="ent_w",
            game_system="D&D 5e",
            tone="épico",
            genre="fantasía",
            state=CampaignState.PAUSADA,
            players=[player],
            player_character_entity_ids=["ent_pc1"],
            session_entity_ids=["ent_ses1"],
            active_plot_entity_ids=["ent_plot"],
            active_faction_entity_ids=["ent_fac"],
            active_location_entity_ids=["ent_loc"],
            secret_entity_ids=["ent_sec"],
            clue_entity_ids=["ent_clue"],
            clock_ids=["clk_01"],
            private_notes=["n1"],
            public_summaries=["s1"],
            visibility_rules={"gm": True},
            history=["h1"],
            metadata={"key": "val"},
        )
        j = c.to_dict()
        c2 = Campaign.from_dict(j)
        assert c2.id == c.id
        assert c2.name == c.name
        assert c2.description == c.description
        assert c2.world_entity_id == c.world_entity_id
        assert c2.game_system == c.game_system
        assert c2.tone == c.tone
        assert c2.genre == c.genre
        assert c2.state == c.state
        assert len(c2.players) == 1
        assert c2.players[0].id == c.players[0].id
        assert c2.players[0].name == c.players[0].name
        assert c2.player_character_entity_ids == c.player_character_entity_ids
        assert c2.session_entity_ids == c.session_entity_ids
        assert c2.active_plot_entity_ids == c.active_plot_entity_ids
        assert c2.active_faction_entity_ids == c.active_faction_entity_ids
        assert c2.active_location_entity_ids == c.active_location_entity_ids
        assert c2.secret_entity_ids == c.secret_entity_ids
        assert c2.clue_entity_ids == c.clue_entity_ids
        assert c2.clock_ids == c.clock_ids
        assert c2.private_notes == c.private_notes
        assert c2.public_summaries == c.public_summaries
        assert c2.visibility_rules == c.visibility_rules
        assert c2.history == c.history
        assert c2.metadata == c.metadata

    def test_created_at_autogenerated(self):
        c = Campaign(name="Test")
        assert c.created_at != ""
        assert "T" in c.created_at


# ═══════════════════════════════════════════════════════════════════════
# PlayerCharacterProfile
# ═══════════════════════════════════════════════════════════════════════


class TestPlayerCharacterProfile:
    def test_minimal_creation(self):
        pcp = PlayerCharacterProfile(entity_id="ent_gandalf")
        assert pcp.entity_id == "ent_gandalf"
        assert pcp.id.startswith("prof_")
        assert pcp.player_id == ""
        assert pcp.objectives == []
        assert pcp.backstory == ""
        assert pcp.created_at != ""

    def test_entity_id_mandatory_in_constructor(self):
        pcp = PlayerCharacterProfile(entity_id="ent_123")
        assert pcp.entity_id == "ent_123"

    def test_empty_entity_id_allowed_in_constructor(self):
        """entity_id is mandatory per domain rules, but technically
        the dataclass allows empty string in constructor.
        Validation of non-empty is done in CampaignService/schema."""
        pcp = PlayerCharacterProfile(entity_id="")
        assert pcp.entity_id == ""

    def test_full_fields(self):
        pcp = PlayerCharacterProfile(
            id="prof_abc",
            entity_id="ent_gandalf",
            player_id="plr_juan",
            objectives=["Destruir el anillo"],
            backstory="Un mago sabio",
            secret_ids=["sec_1"],
            known_entity_ids=["ent_frodo"],
            known_secret_ids=["sec_2"],
            known_clue_ids=["clue_1"],
            unknown_entity_ids=["ent_sauron"],
            unknown_secret_ids=["sec_3"],
            unknown_clue_ids=["clue_2"],
            personal_arc_ids=["arc_1"],
            debt_ids=["debt_1"],
            promise_ids=["prom_1"],
            conflict_ids=["conf_1"],
            current_state="activo",
            session_ids=["ses_1"],
            metadata={"alignment": "good"},
        )
        assert pcp.entity_id == "ent_gandalf"
        assert pcp.player_id == "plr_juan"
        assert pcp.objectives == ["Destruir el anillo"]
        assert pcp.backstory == "Un mago sabio"
        assert pcp.secret_ids == ["sec_1"]
        assert pcp.known_entity_ids == ["ent_frodo"]
        assert pcp.known_secret_ids == ["sec_2"]
        assert pcp.known_clue_ids == ["clue_1"]
        assert pcp.unknown_entity_ids == ["ent_sauron"]
        assert pcp.unknown_secret_ids == ["sec_3"]
        assert pcp.unknown_clue_ids == ["clue_2"]
        assert pcp.personal_arc_ids == ["arc_1"]
        assert pcp.debt_ids == ["debt_1"]
        assert pcp.promise_ids == ["prom_1"]
        assert pcp.conflict_ids == ["conf_1"]
        assert pcp.current_state == "activo"
        assert pcp.session_ids == ["ses_1"]
        assert pcp.metadata == {"alignment": "good"}

    def test_to_dict(self):
        pcp = PlayerCharacterProfile(
            id="prof_001",
            entity_id="ent_gandalf",
            player_id="plr_juan",
            objectives=["obj1"],
        )
        d = pcp.to_dict()
        assert d["id"] == "prof_001"
        assert d["entity_id"] == "ent_gandalf"
        assert d["player_id"] == "plr_juan"
        assert d["objectives"] == ["obj1"]
        assert d["backstory"] == ""
        assert d["session_ids"] == []

    def test_from_dict(self):
        data = {
            "id": "prof_002",
            "entity_id": "ent_frodo",
            "player_id": "plr_maria",
            "objectives": ["Llevar el anillo"],
            "backstory": "Un hobbit",
            "secret_ids": [],
            "known_entity_ids": ["ent_gandalf"],
            "known_secret_ids": [],
            "known_clue_ids": [],
            "unknown_entity_ids": [],
            "unknown_secret_ids": [],
            "unknown_clue_ids": [],
            "personal_arc_ids": [],
            "debt_ids": [],
            "promise_ids": [],
            "conflict_ids": [],
            "current_state": "activo",
            "session_ids": [],
            "metadata": {},
            "created_at": "2026-06-01T00:00:00Z",
            "updated_at": "2026-06-01T00:00:00Z",
        }
        pcp = PlayerCharacterProfile.from_dict(data)
        assert pcp.id == "prof_002"
        assert pcp.entity_id == "ent_frodo"
        assert pcp.player_id == "plr_maria"
        assert pcp.objectives == ["Llevar el anillo"]
        assert pcp.known_entity_ids == ["ent_gandalf"]

    def test_from_dict_empty(self):
        pcp = PlayerCharacterProfile.from_dict({})
        assert pcp.entity_id == ""
        # id is autogenerated by __post_init__
        assert pcp.id.startswith("prof_")
        assert pcp.player_id == ""

    def test_from_dict_missing_entity_id(self):
        """entity_id missing → defaults to empty string."""
        pcp = PlayerCharacterProfile.from_dict({"player_id": "plr_x"})
        assert pcp.entity_id == ""
        assert pcp.player_id == "plr_x"

    def test_roundtrip(self):
        pcp = PlayerCharacterProfile(
            entity_id="ent_gandalf",
            player_id="plr_juan",
            objectives=["obj1", "obj2"],
            backstory="Historia larga",
            secret_ids=["sec_a"],
            known_entity_ids=["ent_e1"],
            known_secret_ids=["sec_k1"],
            known_clue_ids=["clue_k1"],
            unknown_entity_ids=["ent_u1"],
            unknown_secret_ids=["sec_u1"],
            unknown_clue_ids=["clue_u1"],
            personal_arc_ids=["arc_hero"],
            debt_ids=["debt_to_elf"],
            promise_ids=["promise_to_frodo"],
            conflict_ids=["inner_darkness"],
            current_state="activo",
            session_ids=["ses_01", "ses_02"],
            metadata={"level": 5},
        )
        j = pcp.to_dict()
        pcp2 = PlayerCharacterProfile.from_dict(j)
        assert pcp2.id == pcp.id
        assert pcp2.entity_id == pcp.entity_id
        assert pcp2.player_id == pcp.player_id
        assert pcp2.objectives == pcp.objectives
        assert pcp2.backstory == pcp.backstory
        assert pcp2.secret_ids == pcp.secret_ids
        assert pcp2.known_entity_ids == pcp.known_entity_ids
        assert pcp2.known_secret_ids == pcp.known_secret_ids
        assert pcp2.known_clue_ids == pcp.known_clue_ids
        assert pcp2.unknown_entity_ids == pcp.unknown_entity_ids
        assert pcp2.unknown_secret_ids == pcp.unknown_secret_ids
        assert pcp2.unknown_clue_ids == pcp.unknown_clue_ids
        assert pcp2.personal_arc_ids == pcp.personal_arc_ids
        assert pcp2.debt_ids == pcp.debt_ids
        assert pcp2.promise_ids == pcp.promise_ids
        assert pcp2.conflict_ids == pcp.conflict_ids
        assert pcp2.current_state == pcp.current_state
        assert pcp2.session_ids == pcp.session_ids
        assert pcp2.metadata == pcp.metadata

    def test_autogenerated_id_unique(self):
        p1 = PlayerCharacterProfile(entity_id="ent_a")
        p2 = PlayerCharacterProfile(entity_id="ent_b")
        assert p1.id != p2.id
        assert p1.id.startswith("prof_")


# ═══════════════════════════════════════════════════════════════════════
# CampaignClock
# ═══════════════════════════════════════════════════════════════════════


class TestCampaignClock:
    def test_minimal_creation(self):
        ck = CampaignClock(name="El Culto avanza")
        assert ck.name == "El Culto avanza"
        assert ck.id.startswith("clk_")
        assert ck.max_value == 4
        assert ck.current_value == 0
        assert ck.state == CampaignClockState.active
        assert ck.visibility_state == "privado"

    def test_full_fields(self):
        ck = CampaignClock(
            id="clk_001",
            name="Invasión",
            description="Los orcos avanzan",
            linked_entity_ids=["ent_orcos"],
            current_value=2,
            max_value=6,
            state=CampaignClockState.paused,
            visibility_state="visible_jugadores",
            metadata={"urgency": "high"},
        )
        assert ck.id == "clk_001"
        assert ck.name == "Invasión"
        assert ck.description == "Los orcos avanzan"
        assert ck.linked_entity_ids == ["ent_orcos"]
        assert ck.current_value == 2
        assert ck.max_value == 6
        assert ck.state == CampaignClockState.paused
        assert ck.visibility_state == "visible_jugadores"
        assert ck.metadata == {"urgency": "high"}

    def test_to_dict(self):
        ck = CampaignClock(
            id="clk_a",
            name="Reloj A",
            max_value=4,
            current_value=2,
            state=CampaignClockState.completed,
            linked_entity_ids=["ent_x"],
        )
        d = ck.to_dict()
        assert d["id"] == "clk_a"
        assert d["name"] == "Reloj A"
        assert d["current_value"] == 2
        assert d["max_value"] == 4
        assert d["state"] == "completed"
        assert d["linked_entity_ids"] == ["ent_x"]

    def test_from_dict(self):
        data = {
            "id": "clk_b",
            "name": "Reloj B",
            "description": "desc",
            "linked_entity_ids": ["ent_y"],
            "current_value": 1,
            "max_value": 3,
            "state": "paused",
            "visibility_state": "visible_usuario",
            "metadata": {},
            "created_at": "2026-06-01T00:00:00Z",
            "updated_at": "2026-06-01T00:00:00Z",
        }
        ck = CampaignClock.from_dict(data)
        assert ck.id == "clk_b"
        assert ck.name == "Reloj B"
        assert ck.current_value == 1
        assert ck.max_value == 3
        assert ck.state == CampaignClockState.paused

    def test_from_dict_empty(self):
        ck = CampaignClock.from_dict({})
        assert ck.name == ""
        # id is autogenerated by __post_init__
        assert ck.id.startswith("clk_")
        assert ck.max_value == 4

    def test_from_dict_invalid_state(self):
        ck = CampaignClock.from_dict({"name": "X", "state": "invalid"})
        assert ck.state == CampaignClockState.active

    def test_roundtrip(self):
        ck = CampaignClock(
            name="Amenaza",
            description="Avance del mal",
            linked_entity_ids=["ent_bad"],
            current_value=3,
            max_value=8,
            state=CampaignClockState.paused,
            visibility_state="visible_jugadores",
            metadata={"type": "faction"},
        )
        j = ck.to_dict()
        ck2 = CampaignClock.from_dict(j)
        assert ck2.id == ck.id
        assert ck2.name == ck.name
        assert ck2.description == ck.description
        assert ck2.linked_entity_ids == ck.linked_entity_ids
        assert ck2.current_value == ck.current_value
        assert ck2.max_value == ck.max_value
        assert ck2.state == ck.state
        assert ck2.visibility_state == ck.visibility_state
        assert ck2.metadata == ck.metadata

    def test_max_value_default(self):
        ck = CampaignClock(name="Test")
        assert ck.max_value == 4
        assert ck.current_value == 0

    def test_autogenerated_id_unique(self):
        c1 = CampaignClock(name="A")
        c2 = CampaignClock(name="B")
        assert c1.id != c2.id
        assert c1.id.startswith("clk_")


# ═══════════════════════════════════════════════════════════════════════
# Integration: models don't depend on persistence/services/UI/IA
# ═══════════════════════════════════════════════════════════════════════


class TestNoDependencies:
    """Verify domain models are self-contained (no persistence, services, UI, or IA imports)."""

    def test_campaign_models_no_external_imports(self):
        import packages.domain.campaign_models as m
        allowed = {
            "annotations", "dataclasses", "datetime", "enum", "typing", "uuid",
            "__future__", "dataclass", "field", "timezone", "Enum", "Any", "uuid4",
            "datetime", "CampaignState", "CampaignClockState", "CampaignPlayer",
            "Campaign", "PlayerCharacterProfile", "CampaignClock",
            "_now", "_parse_enum", "_parse_list", "_parse_int", "_parse_str", "_parse_dict",
        }
        for name in dir(m):
            if name.startswith("_") or name in allowed:
                continue
            # Should not import anything from other packages
            if hasattr(getattr(m, name), "__module__"):
                mod = getattr(m, name).__module__
                assert mod.startswith("packages.domain.campaign_models") or mod in {
                    "dataclasses", "datetime", "enum", "typing", "uuid", "builtins",
                }, f"Unexpected import: {name} from {mod}"
