"""Campaign domain models — B20-T01.

Campaign, CampaignPlayer, PlayerCharacterProfile, and CampaignClock
implement the role-playing campaign layer (§20.2, §20.3).

Design rules:
  1. PlayerCharacter = NarrativeEntity + PlayerCharacterProfile
     (NOT a parallel character model — entity_id points to an existing
     NarrativeEntity of type PERSONAJE).
  2. Sessions = referential entity IDs only (no SessionPrep/LiveSession in B20).
  3. Campaign relations use the general RelationService (no campaign-specific
     relation model).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── Enums ──────────────────────────────────────────────────────────────


class CampaignState(str, Enum):
    ACTIVA = "activa"
    PAUSADA = "pausada"
    COMPLETADA = "completada"
    ARCHIVADA = "archivada"


class CampaignClockState(str, Enum):
    active = "active"
    paused = "paused"
    completed = "completed"
    archived = "archived"


# ── Helpers ────────────────────────────────────────────────────────────


def _parse_enum(enum_cls, value, default):
    if isinstance(value, enum_cls):
        return value
    if isinstance(value, str):
        try:
            return enum_cls(value)
        except ValueError:
            pass
    return default


def _parse_list(value):
    return list(value) if isinstance(value, list) else []


def _parse_str(value, default=""):
    return value if isinstance(value, str) else default


def _parse_int(value, default=0):
    if isinstance(value, int) and not isinstance(value, bool):
        return value
    if isinstance(value, (str, float)):
        try:
            return int(value)
        except (ValueError, TypeError):
            pass
    return default


def _parse_dict(value):
    return value if isinstance(value, dict) else {}


# ── CampaignPlayer ─────────────────────────────────────────────────────


@dataclass
class CampaignPlayer:
    """Minimal player model — NOT a full user account.

    id is autogenerated (plr_<uuid_hex[:8]>) if not provided.
    PlayerCharacterProfile.player_id references this id.
    """
    name: str
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str = ""

    def __post_init__(self):
        if not self.id:
            self.id = f"plr_{uuid4().hex[:8]}"

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CampaignPlayer:
        if not isinstance(data, dict):
            return cls(name="")
        return cls(
            name=_parse_str(data.get("name"), ""),
            metadata=_parse_dict(data.get("metadata")),
            id=_parse_str(data.get("id"), ""),
        )


# ── Campaign ───────────────────────────────────────────────────────────


@dataclass
class Campaign:
    """Campaign container — organises narrative entities into a playable RPG campaign.

    Covers todos los 21 puntos de §20.2 del contrato de fases.
    players is list[CampaignPlayer], not bare strings.
    """
    name: str
    id: str = ""
    description: str = ""
    world_entity_id: str | None = None
    game_system: str = ""
    tone: str = ""
    genre: str = ""
    state: CampaignState = CampaignState.ACTIVA
    players: list[CampaignPlayer] = field(default_factory=list)
    player_character_entity_ids: list[str] = field(default_factory=list)
    session_entity_ids: list[str] = field(default_factory=list)
    active_plot_entity_ids: list[str] = field(default_factory=list)
    active_faction_entity_ids: list[str] = field(default_factory=list)
    active_location_entity_ids: list[str] = field(default_factory=list)
    secret_entity_ids: list[str] = field(default_factory=list)
    clue_entity_ids: list[str] = field(default_factory=list)
    clock_ids: list[str] = field(default_factory=list)
    private_notes: list[str] = field(default_factory=list)
    public_summaries: list[str] = field(default_factory=list)
    visibility_rules: dict[str, Any] = field(default_factory=dict)
    history: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    updated_at: str = ""

    def __post_init__(self):
        if not self.id:
            self.id = uuid4().hex[:12]
        now = _now()
        if not self.created_at:
            self.created_at = now
        if not self.updated_at:
            self.updated_at = now

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "world_entity_id": self.world_entity_id,
            "game_system": self.game_system,
            "tone": self.tone,
            "genre": self.genre,
            "state": self.state.value,
            "players": [p.to_dict() for p in self.players],
            "player_character_entity_ids": self.player_character_entity_ids,
            "session_entity_ids": self.session_entity_ids,
            "active_plot_entity_ids": self.active_plot_entity_ids,
            "active_faction_entity_ids": self.active_faction_entity_ids,
            "active_location_entity_ids": self.active_location_entity_ids,
            "secret_entity_ids": self.secret_entity_ids,
            "clue_entity_ids": self.clue_entity_ids,
            "clock_ids": self.clock_ids,
            "private_notes": self.private_notes,
            "public_summaries": self.public_summaries,
            "visibility_rules": self.visibility_rules,
            "history": self.history,
            "metadata": self.metadata,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Campaign:
        if not isinstance(data, dict):
            return cls(name="")
        players_raw = _parse_list(data.get("players"))
        players = [CampaignPlayer.from_dict(p) for p in players_raw if isinstance(p, dict)]
        return cls(
            id=_parse_str(data.get("id"), ""),
            name=_parse_str(data.get("name"), ""),
            description=_parse_str(data.get("description"), ""),
            world_entity_id=data.get("world_entity_id") if data.get("world_entity_id") else None,
            game_system=_parse_str(data.get("game_system"), ""),
            tone=_parse_str(data.get("tone"), ""),
            genre=_parse_str(data.get("genre"), ""),
            state=_parse_enum(CampaignState, data.get("state"), CampaignState.ACTIVA),
            players=players,
            player_character_entity_ids=_parse_list(data.get("player_character_entity_ids")),
            session_entity_ids=_parse_list(data.get("session_entity_ids")),
            active_plot_entity_ids=_parse_list(data.get("active_plot_entity_ids")),
            active_faction_entity_ids=_parse_list(data.get("active_faction_entity_ids")),
            active_location_entity_ids=_parse_list(data.get("active_location_entity_ids")),
            secret_entity_ids=_parse_list(data.get("secret_entity_ids")),
            clue_entity_ids=_parse_list(data.get("clue_entity_ids")),
            clock_ids=_parse_list(data.get("clock_ids")),
            private_notes=_parse_list(data.get("private_notes")),
            public_summaries=_parse_list(data.get("public_summaries")),
            visibility_rules=_parse_dict(data.get("visibility_rules")),
            history=_parse_list(data.get("history")),
            metadata=_parse_dict(data.get("metadata")),
            created_at=_parse_str(data.get("created_at"), ""),
            updated_at=_parse_str(data.get("updated_at"), ""),
        )


# ── PlayerCharacterProfile ─────────────────────────────────────────────


@dataclass
class PlayerCharacterProfile:
    """Campaign extension for a NarrativeEntity of type PERSONAJE.

    PlayerCharacterProfile extends a NarrativeEntity (EntityType.PERSONAJE).
    It does NOT create a separate character model.

    entity_id is mandatory — it must point to an existing NarrativeEntity.
    player_id references CampaignPlayer.id.
    """
    entity_id: str
    player_id: str = ""
    id: str = ""
    objectives: list[str] = field(default_factory=list)
    backstory: str = ""
    secret_ids: list[str] = field(default_factory=list)
    known_entity_ids: list[str] = field(default_factory=list)
    known_secret_ids: list[str] = field(default_factory=list)
    known_clue_ids: list[str] = field(default_factory=list)
    unknown_entity_ids: list[str] = field(default_factory=list)
    unknown_secret_ids: list[str] = field(default_factory=list)
    unknown_clue_ids: list[str] = field(default_factory=list)
    personal_arc_ids: list[str] = field(default_factory=list)
    debt_ids: list[str] = field(default_factory=list)
    promise_ids: list[str] = field(default_factory=list)
    conflict_ids: list[str] = field(default_factory=list)
    current_state: str = ""
    session_ids: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    updated_at: str = ""

    def __post_init__(self):
        if not self.id:
            self.id = f"prof_{uuid4().hex[:8]}"
        now = _now()
        if not self.created_at:
            self.created_at = now
        if not self.updated_at:
            self.updated_at = now

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "entity_id": self.entity_id,
            "player_id": self.player_id,
            "objectives": self.objectives,
            "backstory": self.backstory,
            "secret_ids": self.secret_ids,
            "known_entity_ids": self.known_entity_ids,
            "known_secret_ids": self.known_secret_ids,
            "known_clue_ids": self.known_clue_ids,
            "unknown_entity_ids": self.unknown_entity_ids,
            "unknown_secret_ids": self.unknown_secret_ids,
            "unknown_clue_ids": self.unknown_clue_ids,
            "personal_arc_ids": self.personal_arc_ids,
            "debt_ids": self.debt_ids,
            "promise_ids": self.promise_ids,
            "conflict_ids": self.conflict_ids,
            "current_state": self.current_state,
            "session_ids": self.session_ids,
            "metadata": self.metadata,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PlayerCharacterProfile:
        if not isinstance(data, dict):
            return cls(entity_id="")
        entity_id = _parse_str(data.get("entity_id"), "")
        return cls(
            entity_id=entity_id,
            player_id=_parse_str(data.get("player_id"), ""),
            id=_parse_str(data.get("id"), ""),
            objectives=_parse_list(data.get("objectives")),
            backstory=_parse_str(data.get("backstory"), ""),
            secret_ids=_parse_list(data.get("secret_ids")),
            known_entity_ids=_parse_list(data.get("known_entity_ids")),
            known_secret_ids=_parse_list(data.get("known_secret_ids")),
            known_clue_ids=_parse_list(data.get("known_clue_ids")),
            unknown_entity_ids=_parse_list(data.get("unknown_entity_ids")),
            unknown_secret_ids=_parse_list(data.get("unknown_secret_ids")),
            unknown_clue_ids=_parse_list(data.get("unknown_clue_ids")),
            personal_arc_ids=_parse_list(data.get("personal_arc_ids")),
            debt_ids=_parse_list(data.get("debt_ids")),
            promise_ids=_parse_list(data.get("promise_ids")),
            conflict_ids=_parse_list(data.get("conflict_ids")),
            current_state=_parse_str(data.get("current_state"), ""),
            session_ids=_parse_list(data.get("session_ids")),
            metadata=_parse_dict(data.get("metadata")),
            created_at=_parse_str(data.get("created_at"), ""),
            updated_at=_parse_str(data.get("updated_at"), ""),
        )


# ── CampaignClock ──────────────────────────────────────────────────────


@dataclass
class CampaignClock:
    """Generic clock / threat tracker — no system-specific mechanics.

    state is typed with CampaignClockState enum.
    """
    name: str
    max_value: int = 4
    id: str = ""
    description: str = ""
    linked_entity_ids: list[str] = field(default_factory=list)
    current_value: int = 0
    state: CampaignClockState = CampaignClockState.active
    visibility_state: str = "privado"
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    updated_at: str = ""
    # ── B22 extension: front/threat fields ──
    faction_id: str | None = None
    front_id: str | None = None
    advance_conditions: list[str] = field(default_factory=list)
    retreat_conditions: list[str] = field(default_factory=list)
    stage_consequences: list[str] = field(default_factory=list)
    session_ids: list[str] = field(default_factory=list)
    affected_entity_ids: list[str] = field(default_factory=list)
    history: list[str] = field(default_factory=list)

    def __post_init__(self):
        if not self.id:
            self.id = f"clk_{uuid4().hex[:6]}"
        now = _now()
        if not self.created_at:
            self.created_at = now
        if not self.updated_at:
            self.updated_at = now

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "linked_entity_ids": self.linked_entity_ids,
            "current_value": self.current_value,
            "max_value": self.max_value,
            "state": self.state.value,
            "visibility_state": self.visibility_state,
            "metadata": self.metadata,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            # B22 extension
            "faction_id": self.faction_id,
            "front_id": self.front_id,
            "advance_conditions": self.advance_conditions,
            "retreat_conditions": self.retreat_conditions,
            "stage_consequences": self.stage_consequences,
            "session_ids": self.session_ids,
            "affected_entity_ids": self.affected_entity_ids,
            "history": self.history,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CampaignClock:
        if not isinstance(data, dict):
            return cls(name="")
        return cls(
            name=_parse_str(data.get("name"), ""),
            max_value=_parse_int(data.get("max_value"), 4),
            id=_parse_str(data.get("id"), ""),
            description=_parse_str(data.get("description"), ""),
            linked_entity_ids=_parse_list(data.get("linked_entity_ids")),
            current_value=_parse_int(data.get("current_value"), 0),
            state=_parse_enum(CampaignClockState, data.get("state"), CampaignClockState.active),
            visibility_state=_parse_str(data.get("visibility_state"), "privado"),
            metadata=_parse_dict(data.get("metadata")),
            created_at=_parse_str(data.get("created_at"), ""),
            updated_at=_parse_str(data.get("updated_at"), ""),
            # B22 extension
            faction_id=data.get("faction_id") if isinstance(data.get("faction_id"), str) and data.get("faction_id") else None,
            front_id=data.get("front_id") if isinstance(data.get("front_id"), str) and data.get("front_id") else None,
            advance_conditions=_parse_list(data.get("advance_conditions")),
            retreat_conditions=_parse_list(data.get("retreat_conditions")),
            stage_consequences=_parse_list(data.get("stage_consequences")),
            session_ids=_parse_list(data.get("session_ids")),
            affected_entity_ids=_parse_list(data.get("affected_entity_ids")),
            history=_parse_list(data.get("history")),
        )
